# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/Users/kimura/Documents/Python/djlp/user_avatar', null=True, upload_to='user_avatar'),
        ),
    ]
